CREATE TABLE series (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id  BIGINT       NOT NULL,
    title         VARCHAR(200) NOT NULL,
    title_key     VARCHAR(200) NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    total_volumes INTEGER,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_series_publisher FOREIGN KEY (publisher_id) REFERENCES publishers (id),
    CONSTRAINT uk_series_publisher_title_key UNIQUE (publisher_id, title_key),
    CONSTRAINT ck_series_total_volumes CHECK (total_volumes IS NULL OR total_volumes >= 1)
);
